// <auto-generated />
namespace ElectionSystem_RWA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dropcolumnoftables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropcolumnoftables));
        
        string IMigrationMetadata.Id
        {
            get { return "201912041051104_dropcolumnoftables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
